### PR TITLE
chore: fix workflow to run for pull requests as well (not just push)

### LINKED ISSUE #7: GitHub Actions not running on PRs
On the PR I opened few days ago, the GitHub Actions didn't run.
As I don't have permissions to the repo, as it was a PR from a fork, I could not see what the problem see.

Actions seem to have run just fine on the previous PR, done by @davidhouweling

### PR DESCRIPTION
**Pull request by davidhouweling**
## Description
When creating pull requests the pipelines weren't triggering, fixing this now.

## Motivation and Context
This resolves #7.

## How Has This Been Tested?
Look down at the build checks...

## Types of changes
- Bug fix (non-breaking change which fixes an issue)

## Checklist:
- [x] My code follows the code style of this project.
- [x] Any documentation has been updated as required.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by davidhouweling** [comment]
@santino it would be good to modify the settings so that the build pipelines are all required.

**Comment by santino** [comment]
It seems to me that all builds are required already.
Am I missing something?

**Review by santino — APPROVED** [review]

**Comment by davidhouweling** [comment]
Not based on #7, with #7 it showed as passing checks even without the build pipelines. You'll need to go into the settings for master branch and make each of the build branches a requirement, or perhaps just 1 of them at least?

**Comment by santino** [comment]
Double checked and things are setup correctly.
Also new PRs issued by dependabot confirm this.
And even on this PR I am waiting for the build checks to complete given the master branch become outdated and they're re-running.

Will merge and close this 🙂

**Pull request merged**
